services:
  postgres:
    image: postgres:16
    container_name: fitly_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fitly_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fitly_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ__USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ__PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auth_services:
    build:
      context: ./src/auth-api
      dockerfile: Dockerfile
    container_name: fitly_auth
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - Jwt__Key=${JWT__KEY} 
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=fitly_auth;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RABBITMQ__HOST=rabbitmq
      - RABBITMQ__PORT=${RABBITMQ__PORT}
      - RABBITMQ__USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ__PASSWORD=${RABBITMQ__PASSWORD}
      - RABBITMQ__VIRTUALHOST=${RABBITMQ__VIRTUALHOST}
    depends_on:
      - postgres
      - rabbitmq

  body_analysis_ai:
    build:
      context: ./src/body-analysis-ai/BodyAnalysisAI
      dockerfile: Dockerfile
    container_name: fitly_body_analysis
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  rabbitmq_data:
